### ISSUE TITLE
Discord message doesn't show up in minecraft

### ISSUE THREAD

**Issue by MrtnsK** [jamesinaxx/FOMO#6]
The message from minecraft can be seen in the discord channel, but the message from the discord server doesn't appear in minecraft. I didn't find any particular configuration on internet to fix this. Is there a certain way to make it work ?

also there's unwanted char that appear in the discord message :
![image](https://user-images.githubusercontent.com/36154624/118038015-de29fc00-b36e-11eb-9cbc-adf892a63584.png)

thanks in advance

**Comment by jamesinaxx** [comment]
About the unwanted characters, I am working on this. In case you're curious, it is because some plugins mess with name colors and then when FOMO gets the name it gets it with the colors and discord just reads those as plain text.

As for the D-M messages not working, I am not 100% sure why that is. Could you attach your config file (with token censored), Minecraft and server software version, and any logs/errors that happen when you send a message in Discord? There's not a lot I can do until I have more info

**Comment by jamesinaxx** [comment]
*Also if you could attach FOMO version that would be awesome

**Comment by MrtnsK** [comment]
May a regex as filter would fix that ?

I'm using FOMO 0.4, Spigot server on 1.16.5 and Minecraft 1.16.5.
I also have EssentialX 2.18.2.0, WorldEdit 7.2.5 and WorldEdit Selection Visualizer 2.0.8
![Capture d’écran 2021-05-13 131958](https://user-images.githubusercontent.com/36154624/118118963-f0974a80-b3ed-11eb-91bd-02436e41fa33.png)

**Comment by jamesinaxx** [comment]
Thank you for the suggestion I will give that a shot

As for the other issue, I could not replicate it. If you could double-check the values in your config, specifically channel id, and make sure that there are no errors as the plugin starts up.

**Comment by jamesinaxx** [comment]
I have fixed the color codes issue, I will release it in the next patch as it's not the biggest issue

**Comment by MrtnsK** [comment]
Nice about the color codes issue!
I double check the config file, everything is right
Here is the exact error : 
![image](https://user-images.githubusercontent.com/36154624/118141889-2518ff80-b40a-11eb-8b17-fc8a541f26e4.png)
to transmit the msg from discord to minecraft we don't have to use any prefix right ?
you juste have to write your message, not something like "!say "hello world"" ?

**Comment by JAKOPUFF-remasterd** [comment]
im having the same problem but im using 1.16.4

**Comment by jamesinaxx** [comment]
Okay thank you for the logs

This is a known issue on v0.4, if you could try updating to [v0.4.1](https://github.com/jamesinaxx/FOMO/releases/latest) it should fix this issue!

**Comment by jamesinaxx** [comment]
Re-open this issue  if you have any more problems after updating
